#ifndef MODEMAUDIOPLAYER_H
#define MODEMAUDIOPLAYER_H

#include <vector>
#include <portaudio.h>

namespace swmodem {

/// ModemAudioPlayer plays the audio generated by modulation
class ModemAudioPlayer {
public:
    /// Construct a new ModemAudioPlayer
    ModemAudioPlayer();

    /// Release ModemAudioPlayer resources
    ~ModemAudioPlayer();

    /// Play modulated waveform data
    /// @param waveform modulated audio data
    /// @param sample_rate audio sample rate
    void play(const std::vector<double>& waveform, double sample_rate);

private:
    /// Audio data storage
    struct AudioData {
        const std::vector<double>* waveform;
        size_t index;
    };

    /// Audio callback function for playback
    static int audio_callback(
        const void *input, void *output,
        unsigned long frame_count,
        const PaStreamCallbackTimeInfo* time_info,
        PaStreamCallbackFlags status_flags,
        void* user_data
    );

    PaStream* stream;
    bool is_initialized;
};

}

#endif //MODEMAUDIOPLAYER_H
